/**
 * Bakes the handful of Simple Icons path strings we actually use into
 * src/data/icons.ts, so neither the site bundle nor the README generator has to
 * ship the full 3000-icon package.
 *
 *   node scripts/gen-icons.mjs
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { createRequire } from 'node:module'

const require = createRequire(import.meta.url)
const si = require('simple-icons')
const __dirname = path.dirname(fileURLToPath(import.meta.url))

/** slug -> [simple-icons export, display label, brand colour override] */
const WANTED = [
  ['react', 'siReact', 'React', null],
  ['three', 'siThreedotjs', 'Three.js', '#FFFFFF'],
  ['typescript', 'siTypescript', 'TypeScript', null],
  ['next', 'siNextdotjs', 'Next.js', '#FFFFFF'],
  ['webgl', 'siWebgl', 'WebGL', '#FF4D4D'],
  ['tailwind', 'siTailwindcss', 'Tailwind', null],
  ['node', 'siNodedotjs', 'Node.js', null],
  ['python', 'siPython', 'Python', null],
  ['blender', 'siBlender', 'Blender', null],
  ['gemini', 'siGooglegemini', 'Gemini AI', null],
  ['vite', 'siVite', 'Vite', null],
  ['javascript', 'siJavascript', 'JavaScript', null],
  ['github', 'siGithub', 'GitHub', '#FFFFFF'],
  ['x', 'siX', 'X', '#FFFFFF'],
  ['gmail', 'siGmail', 'Email', null],
  ['blob', 'siBabylondotjs', 'Babylon.js', '#E05A5F'],
]

const entries = WANTED.map(([slug, key, label, colour]) => {
  const icon = si[key]
  if (!icon) throw new Error(`simple-icons is missing ${key}`)
  return `  ${slug}: {\n    label: ${JSON.stringify(label)},\n    hex: ${JSON.stringify(
    colour ?? `#${icon.hex}`,
  )},\n    path: ${JSON.stringify(icon.path)},\n  },`
}).join('\n')

const out = `// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// Source: simple-icons (CC0). Each path is drawn in a 24x24 viewBox.

export type Icon = { label: string; hex: string; path: string }

export const icons = {
${entries}
} satisfies Record<string, Icon>

export type IconSlug = keyof typeof icons
`

const target = path.join(__dirname, '..', 'src', 'data', 'icons.ts')
fs.mkdirSync(path.dirname(target), { recursive: true })
fs.writeFileSync(target, out)
console.log(`✓ wrote ${path.relative(process.cwd(), target)} (${WANTED.length} icons)`)
